FROM node:12 as build
RUN npx tech-radar-generator -i tech-radar-data.json -o /opt/radar

FROM nginx:1.15.9
WORKDIR /opt/radar
COPY --from=build /opt/radar .
COPY default.template /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]